### ISSUE TITLE
hawtio console don't have FormAuth plugin.

### ISSUE THREAD

**Issue by yakir3** [hawtio/hawtio-online#101]
hi, I deploy hawtio console as K8S. But i can't login with K8S serviceaccount.

####Here is my operate:
```
./scripts/generate-serving.sh
kubectl apply -k deploy/k8s/namespace
```

####My K8S resources already generate
![image](https://user-images.githubusercontent.com/30774576/158972324-0f339834-93fb-4183-9e9c-5c7920f536d6.png)

The problem :
![image](https://user-images.githubusercontent.com/30774576/158970134-2c307590-9657-4cd2-a34c-9b576f89a7d9.png)

I can't to logout or login, please help me ...

**Comment by tadayosi** [comment]
Hi @yakir3,
I just re-published the docker image. Can you try it again?

**Comment by yakir3** [comment]
> Hi @yakir3, I just re-published the docker image. Can you try it again?

It's work. Thanks
