### ISSUE TITLE
Hawtio online : Internal Server error

### ISSUE THREAD

**Issue by midhunweb** [hawtio/hawtio-online#120]
I have a number of services running on a Kubernetes cluster. One of them have camel routes which I need to monitor. I am using hawtio online for it. But whenever I restart my service pod, Hawtio shows internal server error. I need to redeploy hawtio online to get it working again. Do anyone know the reason and solution for this issue? Also where is the default location of log files?

**Comment by tadayosi** [comment]
You can get the logs from the Hawtio Online pod directly:
```
kubectl logs -f hawtio-online-7bdc6cfbf8-r5kcp
```

> But whenever I restart my service pod, Hawtio shows internal server error. I need to redeploy hawtio online to get it working again.

It is weird. Hawtio should periodically check on the cluster and get the updated list of pods. Note Hawtio Online directly connects to a pod, not via a service, so you need to reconnect to a newly created pod each time you've recreated it.

Also, if it still doesn't help, how many routes in a Camel app?  If the number is very large (e.g. >100) you might need to tune the max memory limit for the Hawtio Online container.

**Comment by Abhilash-as** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/28435089/175887175-ba109d89-15f1-49d4-9f0c-0e945829bf2a.png)

What might be the reason for this file name too long issue

**Comment by tadayosi** [comment]
May I ask pasting the log as text in the code block instead of screenshot?  It's hard for us to inspect an image :confused:

**Comment by tadayosi** [comment]
What's the version of Hawtio Online image you are using?  What's the result of this command?
```
kubectl get deployment hawtio-online -o jsonpath='{$.spec.template.spec.containers[:1].image}'
```
Also have you specified `HAWTIO_ONLINE_RBAC_ACL` env var other than default?  What's the value of the env variable then?

**Comment by Abhilash-as** [comment]
The result of the above command is
`hawtio/online`

When we created new user with viewer role we wasn't able to see the name of containers. So we have changed the `HAWTIO_ONLINE_RBAC_ACL` to use the values from ConfigMap like this.

```
- name: HAWTIO_ONLINE_RBAC_ACL
          valueFrom:
            configMapKeyRef:
              key: ACL.yaml
              name: hawtio-rbac
```

**Comment by tadayosi** [comment]
The `HAWTIO_ONLINE_RBAC_ACL` env var should be a path to `ACL.yaml` (e.g. `/etc/hawtio/rbac/ACL.yaml`), but your setting puts the entire content of `ACL.yaml` to the env var. If you want to modify the content of `ACL.yaml`, just edit the `hawtio-rbac` config map.

**Comment by Abhilash-as** [comment]
But by default its referring to some  file location....right?. So how it will be taken from config map.
So do we need to add such a file in that location?

**Comment by tadayosi** [comment]
Yes, by default and it should refer to a file location, not the content of it. And if you see the `volumes` and `volumeMounts` in the `hawtio-online` deployment, you'll see how the `ACL.yaml` file in the `hawtio-rbac` config map is mount to `/etc/hawtio/rbac/ACL.yaml`. You don't need to change the env var unless you want to do something more creative.

**Comment by Abhilash-as** [comment]
Thanks for the Information,
We were tried this only because our user with viewer role wasn't able to see the containers. When logged in using newly created service account with viewer role the containers name are not listing while the same time user with admin role can see the list of pods. When checked in developer options its showing like 403 forbidden. User not authorized

What might be the reason for this?

While logging in with viewer role
![image](https://user-images.githubusercontent.com/28435089/175922609-4a578aa4-78b9-4360-91d2-d2504c9d95d1.png)

While logging with admin role
![image](https://user-images.githubusercontent.com/28435089/175922726-d26ac152-d6d0-4613-9cf6-57a5a4f688e5.png)

**Comment by tadayosi** [comment]
OK, so it's the same issue as #121. Let's close this one and discuss the issue there.
