### ISSUE TITLE
Hawtio online: RBAC not working

### ISSUE THREAD

**Issue by midhunweb** [hawtio/hawtio-online#121]
The viewer role in hawtio online is not working. The pods are not identified(403 unauthorized) when I login as a user with the viewer role. But the admin role is working. Is there something I am missing?

**Comment by Abhilash-as** [comment]
When logged in using newly created service account with viewer role the containers name are not listing while the same time user with admin role can see the list of pods. When checked in developer options its showing like 403 forbidden. User not authorized

What might be the reason for this?

While logging in with viewer role
![image](https://user-images.githubusercontent.com/28435089/175930868-2f00521a-6b86-4ecb-a0e6-f72367c3a294.png)


While logging with admin role
![image](https://user-images.githubusercontent.com/28435089/175930897-214a2e8b-9311-4b6c-8c0a-5f744a9f9ed6.png)

**Comment by tadayosi** [comment]
Hi, what's the result of the following command?
```
kubectl auth can-i get pods/<pod name> --as <viewer user>
```
It should at least return `yes` so that the given user is recognised as `viewer` role for Hawtio Online.

**Comment by midhunweb** [comment]
> Hi, what's the result of the following command?
> 
> ```
> kubectl auth can-i get pods/<pod name> --as <viewer user>
> ```
> 
> It should at least return `yes` so that the given user is recognised as `viewer` role for Hawtio Online.

I am getting `no` for both `admin` and `viewer` users.  I tried both `get` and `update`.

**Comment by tadayosi** [comment]
OK, then lets give them permissions accordingly so that they are recognised as `veiwer` and `admin` each for Hawtio Online.
https://hawt.io/docs/online/rbac/

**Comment by Abhilash-as** [comment]
Thanks for the help

**Comment by tadayosi** [comment]
What about this role?
```
kubectl create role hawtio-viewer --verb=get,list,watch --resource=pods
```
or if you are using cluster mode:
```
kubectl create clusterrole hawtio-viewer --verb=get,list,watch --resource=pods
```

**Comment by midhunweb** [comment]
I went through all the steps mentioned above.
Created a new role: hawtio-viewer
Created user and role binding.
When I login to hawtio online, I can see the pods but cannot connect to them.
![Screenshot (14)](https://user-images.githubusercontent.com/87698401/176361619-d3980f75-fcb2-478e-8bbc-57ad6e5d6236.png)
![Screenshot (16)](https://user-images.githubusercontent.com/87698401/176361651-1fdba949-51bc-4219-b392-9932d84be285.png)

Note: The cluster admin role doesn't have this issue. It can connect to the pods directly.

**Comment by tadayosi** [comment]
Hmm, I'll take a closer look.

**Comment by midhunweb** [comment]
Thanks for your help and support. It will be good if you can find a solution for this issue.

**Comment by tadayosi** [comment]
Hi @midhunweb,

Turned out there is one more permission required for a viewer role, which is `create` for `authorization.k8s.io/localsubjectaccessreviews`. Please create a viewer role as follows:

```
$ cat <<EOF | kubectl create -f -
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hawtio-viewer
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - localsubjectaccessreviews
  verbs:
  - create
EOF
```

We'll document this somewhere later. Thank you for raising the issue.

**Comment by midhunweb** [comment]
Thank you so much for your help, it is working now.

**Comment by tadayosi** [comment]
Let's keep it open until we improve documentation.

**Comment by phantomjinx** [comment]
Documentation includes access control

- https://hawt.io/docs/online/rbac.html

- https://docs.redhat.com/en/documentation/red_hat_build_of_apache_camel/4.4/html-single/hawtio_diagnostic_console_guide/index#role-based-access-control-for-hawtio-on-openshift-4

**Comment by tadayosi** [comment]
@phantomjinx This part is not yet documented anywhere as far as I know.
https://github.com/hawtio/hawtio-online/issues/121#issuecomment-1171996042

**Comment by phantomjinx** [comment]
PR for missing section -> https://github.com/hawtio/website/pull/60
