### ISSUE TITLE
Hawtio online: Automatic login

### ISSUE THREAD

**Issue by midhunweb** [hawtio/hawtio-online#122]
I am currently doing a project that has camel routes. I am using hawtio online for monitoring as it is in kubernetes cluster. But to login to hawtio online I need to describe secret in kubernetes and get the token. Then I need to give this token in the hawtio online console to login. But my project requires fast logins to hawtio online console. Is there a way, I can automate the process of fetching the token and providing it to hawtio online console?

**Comment by tadayosi** [comment]
Right now, it's out of the scope of Hawtio Online. Possibly you could create a custom script to automate the process or you could find some 3rd party solution for it.

Note we adopt the same approach as K8s dashboard for authenticating users, so anything that can be used for the dashboard shoule be able to be applied to Hawtio Online as well.
https://github.com/kubernetes/dashboard#create-an-authentication-token-rbac
