### ISSUE TITLE
Deploying On Kubernetes Error

### ISSUE THREAD

**Issue by liyongxian** [hawtio/hawtio-online#125]
Hi
 I am currently doing a project using camel-k in kubernetes. and I am using hawtio online for monitoring the routes. I can login the hawtio by token,but it has some errors.The Errors :
![image](https://user-images.githubusercontent.com/18571576/191878979-e9f24067-8061-4494-9d58-c08a0ff1943b.png)
In kubernetes,it should not have Openshift API.
**My Environments:**
**1.Kubernetes:**
![image](https://user-images.githubusercontent.com/18571576/191879461-7de2d3c4-667f-4cef-b883-8c1ce685bec5.png)
**2.Hawtio online:**
kubectl apply -k deploy/k8s/namespace/
**Image Tag:**
hawtio/online:1.14.0
Thanks.
@tadayosi

**Comment by tadayosi** [comment]
@liyongxian That log entry is just a probing of OpenShift API so that Hawtio can detect whether it's running on OpenShift or K8s. You can ignore it. It should be running fine.

**Comment by liyongxian** [comment]
@tadayosi Thanks For your reply.When Do 'Connect' In Hawtio Online Console,It Can not load sucessfully, Loading lasts long time.
Trait of Jolokia in camel-k is enabled,and its protocol is **http**. Thanks.
 
![image](https://user-images.githubusercontent.com/18571576/192408526-3ecfc50b-10fd-45ec-8ddc-47aceed2dc7a.png)

**Comment by tadayosi** [comment]
Hi @liyongxian,

So to monitor Camel K app from Hawtio Online, the most straightforward way is to use **https** with Jolokia trait:
```
 kamel run YourIntegration.java -t jolokia.enabled=true -t jolokia.protocol=https
```
The other (less straightforward) way to achieve this is to add the `hawt.io/protocol=http` annotation to the integration pod. To do so:
```
kubectl patch deployment your-integration -p '{"spec": {"template":{"metadata":{"annotations":{"hawt.io/protocol":"http"}}}} }'
```

**Comment by liyongxian** [comment]
@tadayosi  Thanks for your help,and it works now.But It needs to login,How can I Do?  If It does not need login ,How to set?
![image](https://user-images.githubusercontent.com/18571576/192664673-a0a5fdc9-3c9a-4063-8738-8e4a16a2328b.png)

**Comment by tadayosi** [comment]
@liyongxian Hmm, does the following parameters help?
```
./kamel run YourIntegration.java -t jolokia.enabled=true -t jolokia.protocol=https \
    -t jolokia.use-ssl-client-authentication=false -t jolokia.extended-client-check=false
```

**Comment by liyongxian** [comment]
@tadayosi Thanks.It  works.  When 'Connect', It is Error of 502 Bad Gateway.

![image](https://user-images.githubusercontent.com/18571576/192668367-c605af5b-3cad-4910-a8b7-d2018e12012b.png)

**Comment by tadayosi** [comment]
Which approach have you chosen? Using https or patching deployment?  It looks like you chose the latter, i.e. keeping using http, right?  If so can you try it with https?

**Comment by liyongxian** [comment]
![image](https://user-images.githubusercontent.com/18571576/192669158-c04eea5b-0842-4085-89dd-5619d9664ec3.png)
 After Run:
kubectl patch deployment your-integration -p '{"spec": {"template":{"metadata":{"annotations":{"hawt.io/protocol":"http"}}}} }'

**Comment by tadayosi** [comment]
OK, so if you run it with `-t jolokia.protocol=https` then you don't need to patch the deployment (rather you shouldn't).
Can you only rerun your integration with the params but without `kubectl patch` after that?

**Comment by liyongxian** [comment]
![image](https://user-images.githubusercontent.com/18571576/192669982-448bd5fe-ebb9-49df-b8a1-60fe415247bb.png)
If Do not  ' kubectl patch', It needs to login

![image](https://user-images.githubusercontent.com/18571576/192669846-c2deb8b2-0406-47c0-9ddd-6a95874db707.png)

**Comment by tadayosi** [comment]
Hmm, ok, so I need to check it at my end. Just in case, which K8s distro are you using? Minikube?

**Comment by liyongxian** [comment]
Kubernetes  Management by Rancher.
![image](https://user-images.githubusercontent.com/18571576/192670899-a9c41987-85b5-40f0-a6bc-d608027a961b.png)
Docker version
![image](https://user-images.githubusercontent.com/18571576/192670935-1662468b-48db-4da7-b033-90313778ed12.png)

**Comment by liyongxian** [comment]
@tadayosi  Sorry, When I deployed  camel-k, I set gobal parmaete (jolokia.protocol=http) .Now  It works.
Thanks for help.

**Comment by tadayosi** [comment]
If it's resolved please close. Thanks.
