### ISSUE TITLE
Jolokia http scheme

### ISSUE THREAD

**Issue by robotrader** [hawtio/hawtio-online#129]
Hi!

I can't find any issue tracker|mail list for project, so try to ask here.
We are using jolokia with http sheme (not http**s**) on Kubernetes applications.
hawtio-online can discover pods by port-name=jolokia, but can't connect to them via http.

How can I enable hawtio-online using http scheme instead http**s**?

**Comment by tadayosi** [comment]
You can use `hawt.io/protocol=http` annotation on the pod to specify the scheme.
```
kubectl patch deployment <your-app> -p '{"spec": {"template":{"metadata":{"annotations":{"hawt.io/protocol":"http"}}}} }'
```
