### ISSUE TITLE
Migrate to quay.io

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-online#132]
Since Docker is sunsetting Free Team organisations:
https://web.docker.com/rs/790-SSB-375/images/privatereposfaq.pdf

**Comment by tadayosi** [comment]
Docker free team orgs hasn't sunset but it's good time for us to switch to quay.io starting from v2. @phantomjinx

**Comment by phantomjinx** [comment]
Completed with https://github.com/hawtio/hawtio-online/pull/229
