### ISSUE TITLE
V2 - Avoid using global variables

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-online#143]
Once we have refreshed hawtio-online to a workin state, let's remove usages of global variables like this:
https://github.com/hawtio/hawtio-online/blob/73b6647498674a7cd09e1adf5b1fba8a3d1e1d77/packages/kubernetes-api/api/src/kubernetes-api-init.ts#L8-L13

With the ES module we are based on in v2, there'll be no need to rely on global variables like this. There should be always a smarter method to configure the system between modules.

**Comment by tadayosi** [comment]
cc @phantomjinx

**Comment by phantomjinx** [comment]
Resolved in 2.x.
