### ISSUE TITLE
The use of jolokia GET requests with body is to be discontinued

### ISSUE THREAD

**Issue by phantomjinx** [hawtio/hawtio-online#152]
The jolokia [documentation](https://jolokia.org/reference/html/clients.html#client-javascript) outlines the use of HTTP requests being made using the GET or POST methods with a body.

Despite this, the nginx.js [script](https://github.com/hawtio/hawtio-online/blob/main/docker/nginx.js#L177-L186) has not supported GET requests created in this fashion. Therefore, it will not be implemented in version 2.x either. The result will be that all requests using the GET method must utilise the URI path while POST methods will continue to use the body.

For example, all tests in the [njs test script](https://github.com/hawtio/hawtio-online/blob/main/docker/test.js#L37) now have a POST method added to each request.

**Comment by tadayosi** [comment]
@phantomjinx I still don't get what's the issue here.

> The jolokia [documentation](https://jolokia.org/reference/html/clients.html#client-javascript) outlines the use of HTTP requests being made using the GET or POST methods with a body.
> 
> Despite this, the nginx.js [script](https://github.com/hawtio/hawtio-online/blob/main/docker/nginx.js#L177-L186) has not supported GET requests created in this fashion.

Do you mean `nginx.js` should have supported GET requests **with** a body?  Then I don't think Jolokia has ever supported GET with a body, either. Please help me to understand what's really the problem with it.

**Comment by phantomjinx** [comment]
For the `njs` tests to ever have passed, the `nginx.js` script would have allowed GET / Body requests.

The `nginx.js` script was changed (???) at some point to not [support](https://github.com/hawtio/hawtio-online/blob/main/docker/nginx.js#L182-L227) this sittuation, if it ever did??

So having witnessed the `njs` tests all returning 502 errors, I went to check the jolokia documentation and found that, in limited circumstances, such GET / Body requests are legitimate.

This issue though is confirming that going forward, with the use-case being such a corner issue, we are not going to change anything to support such requests. In summary, I am confirming the status-quo and updated the `njs` tests accordingly.

**Comment by tadayosi** [comment]
Btw, when I run the njs tests on 1.x branch it passes all fine:
```console
$  yarn test:nginx 
yarn run v1.22.19
$ cd docker/ && HAWTIO_ONLINE_RBAC_ACL= njs test.js
Done in 0.09s.
```
Could you confirm it's the same with you?  If not, something should be different in your specific environment.

**Comment by phantomjinx** [comment]
I couldn't get an `njs` version old enough for Fedora 37 (0.7.0) so I have ran some [tests](https://github.com/phantomjinx/hawtio-online/actions) on github instead.

It seems that hawtio-online-1.0 does not [run](https://github.com/hawtio/hawtio-online/commit/d129afc0419790f2256412cd5fd6e8e6075bb6bf#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R43) the njs tests as a matter of course. When I have included it, the [tests](https://github.com/phantomjinx/hawtio-online/actions) actually fail to execute with the same result I see locally under njs 0.7+
```
TypeError: (intermediate value)["charCodeAt"] is not a function
    at loadDocuments (js-yaml.js:2495)
    at load (js-yaml.js:2540)
    at safeLoad (js-yaml.js:2562)
    at module (rbac.js:5)
```

Nevertheless, what I did do was [change](https://github.com/hawtio/hawtio-online/commit/d129afc0419790f2256412cd5fd6e8e6075bb6bf#diff-65c0f6f3500fd62457bca3df0215dd65af2494c0721f623d2020035d8af61985R12) the tests to add in console logging and an exit return value if the test failed. Reason I did this and what I am trying to show is that when I ran the tests for version 2.x, they would `Exit 0` even if the promises returned `502` thereby giving a false impression of passing.

Therefore, are you able to confirm that your running of the tests returned expected `200` and `403` status codes?

**Comment by tadayosi** [comment]
@phantomjinx You are looking at a wrong branch. The 1.x line should be `1.x`. `1.x-redhat` branches are for productisation, where `docker/` is not used.

By the way, I use Fedora 38 but I have the old version of `njs` in `.local/bin/`. It's copied manually from the old version of distribution.

**Comment by phantomjinx** [comment]
Hey @tadayosi,

Cool. Got the right branch. Have added the same console logging changes to the test script and re-ran the tests (phew!). However....

https://github.com/phantomjinx/hawtio-online/actions/runs/6466762033/job/17555435325

- The version of `njs` is [expected](https://github.com/phantomjinx/hawtio-online/actions/runs/6466762033/job/17555435325#step:8:27) (0.4.4);
- The tests complete (Green) yet have [errors](https://github.com/phantomjinx/hawtio-online/actions/runs/6466762033/job/17555435325#step:8:35);
- The first test `requestWithViewerRoleTest` fails at `parseRequest()` ([here](https://github.com/phantomjinx/hawtio-online/actions/runs/6466762033/job/17555435325#step:8:33)) due to it being a `GET` request that contains a body not a path;
- The failure is confirmed by a `502` code and the message that the regex could not parse correctly.

**Comment by tadayosi** [comment]
@phantomjinx OK, thanks for your investigation. Now everything is clear to me.

It's a bug in `test.js` not the `nginx.js` itself. Some time ago I made changes to 1.x to support GET requests for hawtio-online:
https://github.com/hawtio/hawtio-online/commit/53f3781efb29d25d56798d43a245614d25eefba0
Before that only POST requests were supported. But due to lack of verbosity in the njs `test.js` test suite, this test bug hasn't been visible since then.

So the correct fix should be just adding `POST` explicitly to each test of `test.js` and what you've already committed 82007487fd250bcc60fdc37aad89ac9d8bd55203 fixes it enough. There's nothing wrong with `nginx.js`.

If you wouldn't mind, please backport 82007487fd250bcc60fdc37aad89ac9d8bd55203 to 1.x just in case. Thank you.

**Comment by phantomjinx** [comment]
Sure thing.

**Comment by tadayosi** [comment]
fixed
