### ISSUE TITLE
Release hawtio-online 2.0.0-beta.1

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-online#184]
I think the `main` branch is in good shape, so it's time for us to release the 1st beta version of 2.0.0. Releasing hawtio-online should be mostly:

- Update the version of `@hawtio/online-shell` (why it's renamed from `@hawtio/online`?). Tag it to the repository and push it.
- Build the container image and publish it to the container registry we choose as the primary release channel.

For the container registry, I think from v2 we can use quay instead of docker.

**Comment by phantomjinx** [comment]
Released 2.0.0 so superceded
