### ISSUE TITLE
Update documentation including README for v2

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-online#185]
We need to update documentation including README.md for v2 before releasing 2.0.0.

**Comment by phantomjinx** [comment]
Updates in
- https://github.com/hawtio/hawtio-online/commit/ac4f2f1521eac9c216088e3f48de4df29924819d
- https://github.com/hawtio/hawtio-online/commit/bcd6dd9570c1485f44daab1e1f6dac9351d01df2
