### ISSUE TITLE
Logout does not seem to work

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-online#189]
Logout should take users to the OpenShift provider specific login page for prompting authentication.

[Screencast from 2023-11-13 14-41-54.webm](https://github.com/hawtio/hawtio-online/assets/156692/ee00e2eb-3268-461a-96ec-d5b5ad1965ac)

**Comment by phantomjinx** [comment]
The logout is working correctly in that when <logout> button is clicked, the token is removed and in its absence, the app redirects to the login provider page. However, on an IBM cluster the login provider <identify> page logs straight back in and hawtio extracts it and logs back in again.

**Comment by tadayosi** [comment]
@phantomjinx I wonder how it worked with hawtio-online 1.x. If it worked well and logged us out from IBM cluster then we could do something similar for the new hawtio-online too.

**Comment by tadayosi** [comment]
The following code is dropped from the new hawtio-online. Isn't it because of that?

https://github.com/hawtio/hawtio-oauth/blob/303d9fe06f48abee7a16c6a6459a9296458de0e3/plugins/osOAuth/osOAuth.helpers.ts#L27-L35
```ts
    authenticatedHttpRequest({
      type: 'DELETE',
      url: uri.toString(),
    }, userDetails).always(() => {
      clearTokenStorage();
      doLogin(OSOAuthConfig, {
        uri: currentURI.toString(),
      });
    });
```

Note https://github.com/openshift/origin/issues/7011 is closed so it doens't seem to be an issue anymore, is it?
