### ISSUE TITLE
Investigate disabling of connect plugin without resorting to hawtconfig.json

### ISSUE THREAD

**Issue by phantomjinx** [hawtio/hawtio-online#200]
The Connect plugin should not be visible in hawtio-online since Discover takes on this functionality. Find a way to disable it more appropriately than resorting to the `hawtconfig.json` file that can be updated by the user.

**Comment by phantomjinx** [comment]
Supercedes PR #197

**Comment by tadayosi** [comment]
I don't see connection between this issue and #197. Do you mean this?
> * Corrects the route of Connect plugin in disabledRoutes
>   * Stops the Connect plugin from being displayed in Online-Shell app
