### ISSUE TITLE
Proxy Jolokia traffic to avoid CORS issues

### ISSUE THREAD

**Issue by astefanutti** [hawtio/hawtio-online#21]
The following change introduced in the OpenShift Ansible playbook openshift/openshift-ansible#5264 breaks the current integration by default as subdomain origins do not match CORS allowed origins configured on the master server.

**Comment by tadayosi** [comment]
I'm curious about how you resolved it. What kind of proxy is it using now?

**Comment by tadayosi** [comment]
@astefanutti Thanks!
