### ISSUE TITLE
About - Component versions are not applied

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-online#211]
`PACKAGE_VERSION_PLACEHOLDER` should be updated to the real package versions.

Also, we don't need to display versions for `Hawtio Kubernetes API`, `Hawtio Management API`, and `Hawtio OAuth`, as we don't publish them independently. The only thing we need to display other than `Hawtio React` is `Hawtio Online`.

![image](https://github.com/hawtio/hawtio-online/assets/156692/2f8bf1cc-520d-4e7d-beb4-e273fa10152a)

**Comment by tadayosi** [comment]
@lhein Important to fix.

**Comment by tadayosi** [comment]
Also, not related to upstream, but `Red Hat Hawtio` doesn't seem right. It should be `Red Hat build of Hawtio`.

**Comment by phantomjinx** [comment]
![Screenshot_20231127_215236](https://github.com/hawtio/hawtio-online/assets/1634180/7c8c297d-0e34-4342-96ad-1793d252d4d6)

**Comment by phantomjinx** [comment]
> Also, not related to upstream, but `Red Hat Hawtio` doesn't seem right. It should be `Red Hat build of Hawtio` for the product.

Addressed downstream.
