### ISSUE TITLE
Support Kubernetes

### ISSUE THREAD

**Issue by astefanutti** [hawtio/hawtio-online#23]

**Comment by ninckblokje** [comment]
Hi,

Is it possible to run hawtio-online on Kubernetes, not on OpenShift?

**Comment by astefanutti** [comment]
For the time being it is not possible, mostly due to the way authentication is setup. I plan to work on bringing Kubernetes support ASAP.

**Comment by ninckblokje** [comment]
Ok. Thanks for the quick reply!

**Comment by mxandeco** [comment]
Hey, is there any progress on this? is the authentication the only blocker for the integration?

**Comment by astefanutti** [comment]
It has yet to be done. The main area task is to enable token-based authentication. The UI should be slightly adapted to managed the lack of user information (as provided by the OpenShift API). On the backend-side, the bits relying on the service signing certificate should be adapted as well.

**Comment by mariuszkopowski** [comment]
Hi any news on that ?

**Comment by anerathil** [comment]
Hey, is there any progress on this?

**Comment by ilyesAj** [comment]
any updates here ?

**Comment by tadayosi** [comment]
Fixed. The remaining brushing-up will be done at #89
