### ISSUE TITLE
Component versions no longer visible in About modal

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-online#256]
I checked the latest deployed instance of hawtio-online and I found:

![image](https://github.com/hawtio/hawtio-online/assets/156692/9ad638b7-a48c-439a-84d4-e8ed2134bafc)

@phantomjinx Maybe it's something you can quickly fix.

**Comment by phantomjinx** [comment]
Sorted. Its something to do with the hawtconfig.json configmap either being present or not. In production, it does not but in upstream it does.
Anyway, now fixed.

**Comment by phantomjinx** [comment]
Reopening this issue since the component versions no longer appear when the app is installed via the operator. When it is installed via the `Makefile`, the component versions appear correctly.

**Comment by phantomjinx** [comment]
Found the reason for this issue and logged in [hawtio-next/#715](https://github.com/hawtio/hawtio-next/issues/715).

**Comment by phantomjinx** [comment]
Workaround is to ensure an empty `productInfo` array property is present in `hawtconfig.json`

**Comment by tadayosi** [comment]
This should be already fixed by hawtio/react 1.2.6.
