### ISSUE TITLE
Should we use official node image?

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-online#260]
I stumbled on this. Is there a reason to use this node image?  I think it's better to use the official image from docker hub. Also, if possible we should upgrade node to 18.

https://github.com/hawtio/hawtio-online/blob/4291ab465b4961dee34e198adbe4b28e377dba3a/Dockerfile#L1

**Comment by phantomjinx** [comment]
Only that we were moving away from docker hub and onto quay for our images. The `jitesoft` organisation provides node images on both docker hub and quay. I'll post a PR for the official node image from docker hub.

**Comment by tadayosi** [comment]
When we say migrating to quay.io, it only means for our distributions, not those we depend. It's about our control on how to release our images. I think it's totally fine to depend on images hosted on docker hub since we cannot expect many of the ecosystem to migrated to quay.io.

**Comment by phantomjinx** [comment]
Completed with #261
