### ISSUE TITLE
Token is displayed instead of logged-in username

### ISSUE THREAD

**Issue by mmelko** [hawtio/hawtio-online#271]
![image](https://github.com/hawtio/hawtio-online/assets/6814482/5dcf9f7a-da9a-47b3-b40b-041116190bb7)

I'd expect that Username should be there instead.

**Comment by phantomjinx** [comment]
How was this screenshot got to?
If using form method for logging in then the only known item is the token and these tokens do not decode to a user name.

**Comment by tadayosi** [comment]
@phantomjinx @mmelko Actually they do. The tokens are in form of [JWT](https://jwt.io/), so by inspecting the `sub` field from the data part, you can even extract the service account name from them.

You can confirm that by doing something like this with [jwt-cli](https://github.com/mike-engel/jwt-cli):
```console
k get secrets <token-secret> -oyaml | yq .data.token | base64 -d | xargs jwt decode
```

I guess you didn't port this part from hawtio-oauth:
https://github.com/hawtio/hawtio-oauth/blob/main/plugins/form/form.module.ts#L36-L46

As I said, the whole reason why we included jwt-decode.js was to perform this on the fly.

**Comment by phantomjinx** [comment]
@tadayosi 

You mean this -> https://github.com/hawtio/hawtio-online/blob/main/packages/oauth/src/form/form-service.ts#L196-L202 ??

**Comment by tadayosi** [comment]
Yes, so it’s there but somehow doesn’t seem to work.

**Comment by phantomjinx** [comment]
It does on JWT tokens but it seems that the tokens specified by `oc whoami -t` (see screenshot) are capable of logging in but cannot be decoded without some extra step.

```
⏚ [: … bin] $ oc whoami -t | base64 -d
���base64: invalid input
⏚ [: … bin] 1 $ oc whoami -t | sed 's/sha256~\(.*\)/\1/g'
lLdhvIq_BA64oW0e0MzycgIKd-co61xVyAzUvsEWrV8
⏚ [: … bin] $ oc whoami -t | sed 's/sha256~\(.*\)/\1/g' | base64 -d
��a��base64: invalid input
⏚ [: … bin] 2 $ oc whoami -t | xargs jwt decode 
The JWT provided is invalid
```

Any thoughts?

**Comment by tadayosi** [comment]
@phantomjinx So look at the code more closely, whenever the decoding fails it just uses a raw token. That should be why the issue happens. We should rather look into why the decoding fails. The original code didn't snub the errors when decoding it.

```ts
      let subject = this.userProfile.getToken()
      try {
        subject = this.getSubjectFromToken(this.userProfile.getToken())
      } catch (err) {
        if (err instanceof Error) log.warn(err.message)
        else log.error(err)
      }
```

**Comment by tadayosi** [comment]
> Any thoughts?

Not sure but you should follow what's described here to acquire the token instead:
https://github.com/hawtio/hawtio-online/blob/main/docs/create-user.md#getting-a-bearer-token

**Comment by phantomjinx** [comment]
We can't really stop a user using the most available token. Even when accessing IBM cloud's OS, I still go to the `Copy Login Command` dropdown which then displays:

![Screenshot_20231220_100225](https://github.com/hawtio/hawtio-online/assets/1634180/2a5b90b8-03ee-467c-bf68-00bc8aece9f9)

This provides a token and it logs in. So I think we need to try and decode how this token is wrapped up to maybe convert back to JWT.

**Comment by phantomjinx** [comment]
[This](https://stackoverflow.com/questions/9316437/how-to-decrypt-a-sha-256-encrypted-string) would suggest that the token is a one-way hash so cannot be easily decoded. Therefore, it would make sense that we use it to get the username from the cluster API server.

**Comment by tadayosi** [comment]
But it wasn't supported. That's why I wrote the dedicated doc: https://github.com/hawtio/hawtio-online/blob/main/docs/create-user.md that users should follow.
But if you really want to support tokens from `oc whoami -t`, then you can go ahead but it should require additional steps to fetch the username from the token.

But one thing that's really odd to me is that basically the form auth is for Kubernetes, not OpenShift, while you can still use it on OpenShift. So that means that with the primary use case users will never use `oc whoami -t` as there's not such command with `kubectl`.

**Comment by phantomjinx** [comment]
> But it wasn't supported. That's why I wrote the dedicated doc: https://github.com/hawtio/hawtio-online/blob/main/docs/create-user.md that users should follow. But if you really want to support tokens from `oc whoami -t`, then you can go ahead but it should require additional steps to fetch the username from the token.

Yes. Agreed.

> But one thing that's really odd to me is that basically the form auth is for Kubernetes, not OpenShift, while you can still use it on OpenShift. So that means that with the primary use case users will never use `oc whoami -t` as there's not such command with `kubectl`.

Indeed, but there is nothing stopping you from using form authentication with Openshift, so means it is a low priority issue.

**Comment by tadayosi** [comment]
> Indeed, but there is nothing stopping you from using form authentication with Openshift, so means it is a low priority issue.

I agree it's low priorty, but am curious why @mmelko followed the step. Is there a doc that suggests it's one of the ways users can set up?  If so, we should rewrite the part.

Unless we explicitly write the steps to use the form auth on OpenShift, users won't dare to use the auth method but use OpenShift OAuth.

**Comment by phantomjinx** [comment]
PR -> https://github.com/hawtio/hawtio-online/pull/275
