### ISSUE TITLE
Remove `HAWTIO_ONLINE_GATEWAY` env var and drop support for non-gateway Nginx deployment

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-online#363]
If I remember correctly, this gateway flag is provided to keep backward compatibility to non-RBAC hawtio-online deployment.
```yaml
            - name: HAWTIO_ONLINE_GATEWAY
              value: 'true'
```
But now, with v2 no one would use the old non-RBAC mode any more. To simplify the Nginx configurations, let's remove the env var and drop support for the non-gateway deployment mode.

**Comment by phantomjinx** [comment]
https://github.com/hawtio/hawtio-online/pull/380.

Will also need change in operator to complete.

**Comment by phantomjinx** [comment]
PR for operator: https://github.com/hawtio/hawtio-operator/pull/113
