### ISSUE TITLE
User is left on a blank page after logging off

### ISSUE THREAD

**Issue by mmuzikar** [hawtio/hawtio-online#407]
When a user logs off from being connected to an app they get redirected to login screen again and if they log in they get navigated back to hawtio online, but there's no content presented. The issue is probably that the same redirect_uri is used, but I guess the users should be redirected back to just /online not /online/<path>

[Peek 2024-03-27 15-32.webm](https://github.com/hawtio/hawtio-online/assets/46345469/c76eda88-5506-441d-b790-03d180e9f67e)

**Comment by mmuzikar** [comment]
Seems like it's no longer an issue

**Comment by phantomjinx** [comment]
Still a problem in development mode.
