### ISSUE TITLE
Provide script to automate client cert generation for OpenShift 4

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-online#57]
Does it make sense to provide a script to automate most of the steps described in https://github.com/hawtio/hawtio-online#openshift-4 so that users can just run it to do the job?

@astefanutti WDYT?

**Comment by astefanutti** [comment]
That's a good idea. For non-developer users, that deploy the console from templates, without having this repository locally, we may want to keep these steps documented, along with the one-liner script option.

Ultimately, these instructions should be performed by the operator.

**Comment by tadayosi** [comment]
Is [ENTESB-11132](https://issues.redhat.com/browse/ENTESB-11132) exactly what the operator should perform?

**Comment by astefanutti** [comment]
> Is ENTESB-11132 exactly what the operator should perform?

Yes, the manual steps required to generate the client certificate should ideally be automated in the operator.

**Comment by tadayosi** [comment]
The operator issue is reported at hawtio/hawtio-operator#25

**Comment by astefanutti** [comment]
> The operator issue is reported at hawtio/hawtio-operator#25

Thanks @tadayosi.
