### ISSUE TITLE
Support Artemis plugin

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-online#58]
Let's include [Artemis plugin](https://github.com/apache/activemq-artemis/tree/master/artemis-hawtio/artemis-plugin) through the intermediary NPM package [artemis-plugin-npm](https://github.com/rh-messaging/artemis-plugin-npm) so that Hawtio Online can manage Artemis brokers on OpenShift.

Related hawtio/hawtio-integration#103

**Comment by tadayosi** [comment]
Blocked by #66

**Comment by tadayosi** [comment]
artemis-plugin-npm 0.1.4 is included now. There is still room for improvements but we can address them in different issues. Closing this.

**Comment by astefanutti** [comment]
Awesome!
