### ISSUE TITLE
DeploymentConfig image reference triggers unnecessary deployments

### ISSUE THREAD

**Issue by vinzent** [hawtio/hawtio-online#62]
I want to run `oc apply -f deployment-cluster-os4.yml` multiple times. But a second run will trigger 2 additional deployments of the DeplyomentConfig.

## Root cause

The ImageChange trigger injects the image reference into `.spec.template.spec.containers[].image` . 

If you run `oc apply -f deployment-cluster-os4.yml` a second time, the image reference is reset to `hawtio/online` triggering the 2nd deployment. That will be canceled immediately due to the ImageChange trigger replacing the image reference again - triggering a 3rd deployment.

## Solution

If one wants to run `oc apply -f deployment-cluster-os4.yml` in a declarative way, you need to remove the DeploymentConfig `.spec.template.spec.containers[].image=hawtio/online` key/value.

## Environment

OpenShift 3.11 (probably same issue also on OpenShift 4, but not tested), Fuse 7.6

**Comment by vinzent** [comment]
its `oc process --local -p KEY=VALUE | oc apply -f -` not `oc apply -f deployment-cluster-os4.yml` directly . Was working on the generated yaml and mixed up some things.

**Comment by tadayosi** [comment]
@vinzent [README](https://github.com/hawtio/hawtio-online#deployment) suggests using `oc new-app -f deployment-namespace.yml -p ROUTE_HOSTNAME=<HOST>`, which is equivalent to `oc process --local -p KEY=VALUE | oc apply -f -`.

Also, `deployment-cluster-os4.yml` is for OpenShift 4. You should not use it for OpenShift 3.x.

**Comment by vinzent** [comment]
>  oc new-app -f deployment-namespace.yml -p ROUTE_HOSTNAME=<HOST>

You're probably right that im doing more than what is documented. The docs only say how to deploy it initially. What I want to achiev is to be able to run `oc apply -f ...` multiple times after the inital deployment without triggering unneeded deployments/rollouts of the pods.

Because the source here and the ImageChange trigger manage the image reference in the container template this is a (small) issue. 

But feel free to close this issue if its a non-goal of hawtio-online of being able to run apply multiple times without triggering unnecessary changes.

> Also, deployment-cluster-os4.yml is for OpenShift 4. You should not use it for OpenShift 3.x

Due to networking security we can't use OS3 method which uses the kube-apiserver pod proxy feature. We need to have a console deployment by networkzone - which only seems (somehow) doable with the OS4 method of deploying which uses SDN to jolokia ports directly (RH support told me that it should be possible).

**Comment by tadayosi** [comment]
Now I see your point. Let's keep it open so hopefully we can come up with a better solution for it.

Meanwhile, FWIW now we recommend using https://github.com/hawtio/hawtio-operator instead of this manual installation.
