### ISSUE TITLE
Replace hawtio-kubernetes-api with kubernetes-client/javascript?

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-online#67]
Is it possible to replace [hawtio-kubernetes-api](https://github.com/hawtio/hawtio-kubernetes-api) with [kubernetes-client/javascript](https://github.com/kubernetes-client/javascript) and even if possible is it worth doing so?  Instead of keeping the homebrewed k8s library it seems valuable to rely on the more actively maintained/popular library.

I guess the biggest challenge is where OpenShift authentication is used.

**Comment by astefanutti** [comment]
That is a good idea. Using the official client would definitely make sense.

However, from the project README, it seems it's only for server-side at the moment:

> For now, the client is implemented for server-side use with node using the request library.
>
> There are future plans to also build a jQuery compatible library but for now, all of the examples and instructions assume the node client.

Besides, as you've mentioned, it would have costs, like integrating with OAuth, making sure WebSocket works, and it supports falling back to polling, ...

From my experience, `hawtio-kubernetes-api` has worked surprisingly well so far, without much maintenance overhead.

**Comment by tadayosi** [comment]
Thanks for your explanation @astefanutti!  Then maintaining `hawtio-kubernetes-api` seems to be a better approach. Closing it.
