### ISSUE TITLE
Should vertical nav be open by default for hawtio-online?

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-online#68]
I see hawtio-online-integration closes the vertical nav by default. I think it makes more sense for hawtio-online doing the same behaviour as it should only show the "Online" plugin effectively.

**Comment by astefanutti** [comment]
That's a good idea. It started with the idea that there may be other plugins added, but as long as there is only the _online_ plugin available, it makes sense to close the vertical nav.

**Comment by tadayosi** [comment]
Thanks for confirmation. I can commit a fix soon.

**Comment by astefanutti** [comment]
I can confirm it works as it's already been deployed on my test cluster thanks to the `ImageStream` auto-magic 😉!
