### ISSUE TITLE
Login should not be prompted when getting 401 in the Integration view

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-online#76]
Sometimes an idle Integration view gets 401 unauthorized errors in the background and thus shows us the login prompt like the following. However, in the context of hawtio-online giving an username/password in the prompt shouldn't resolve the error. We should rather just close the view and reconnect to the pod from the Online view again. Thus it should be better that the prompt simply says we get an unauthorized error in the background and close the view with a single `OK` button, asking the user to reconnect to the pod again.

![Screenshot from 2020-11-18 14-01-21](https://user-images.githubusercontent.com/156692/99485933-bc931d80-29a6-11eb-9778-bc572f9fa858.png)

**Comment by tadayosi** [comment]
Or is there any other root cause that makes the unauthorized errors happen so often on OpenShift?

**Comment by astefanutti** [comment]
I agree prompting username/password is not the ideal UX, yet I wonder what could cause these 401s. Would you know what requests return 401 specifically, or is it any request?

**Comment by tadayosi** [comment]
Basically the Integration console (i.e. JMX plugin) periodically sends Jolokia call in the background to watch any changes in the JMX tree, and it is those requests that may get 401 errors. Most of the times it appears the login session for the OCP mgmt console is timed out and thus causes 401, but in any case once it gets  unrecoverable 401 the console should be closed or reloaded instead of prompting username/password.

**Comment by tadayosi** [comment]
I think this part in the JVM plugin causes the login prompt:
https://github.com/hawtio/hawtio-integration/blob/master/plugins/jvm/ts/jolokia/jolokiaService.ts#L237-L263

**Comment by astefanutti** [comment]
Right, if the token has expired, a better UX would be to redirect to the OpenShift login page, or display a relevant error message at least.
