### ISSUE TITLE
Not able connect the Pod from Hawtio Dashboard (SSL handshake)

### ISSUE THREAD

**Issue by keremceliker** [hawtio/hawtio-online#77]
Is there any suggestion to fix that issue or there something specific/additional i need to do in terms of the NGINX conf file towards that end ?

**_**Related pod seems to be running stable from oc get pod in project..._**

2020/11/19 08:10:44 [error] 18#18: ***5050 peer closed connection in SSL handshake while SSL handshaking to upstream,** client: 10.100.2.1, server: localhost, request: "POST /management/namespaces/maf-tst/pods/https:maf-ui-policegor-549-v6gwk:8778/jolokia/ HTTP/1.1", subrequest: "/proxy/https:10.100.2.10:8778/jolokia/", upstream: "https://10.100.2.10:8778/jolokia/", host: "ca-hawtio-ca-monitoring.apps.xcorp.prod.com", referrer: "https://ca-hawtio-ca-monitoring.apps.xcorp.prod.com/online/online/discover"

**Comment by astefanutti** [comment]
Could you provide more details about the pod that you're trying to connect to with hawtio-online? More specifically, could you provide the configuration of the Jolokia endpoint?

Also, you can try adding the `JAVA_OPTIONS=-Djavax.net.debug=all` environment variable to the target application, and report the log printed during the connection.
