### ISSUE TITLE
Support user-provided SSO/identity providers

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-online#78]
This might be a duplicate of #31 but the idea is to enable integration with SSO/identity providers the user has brought on a k8s cluster for their own apps. I think why currently it's hard to support vanilla k8s #23 for hawtio-online is its tight integration with OpenShift's OAuth mechanism and thus its being part of the OpenShift infra components. Unlike other monitoring components such as Prometheus and Grafana, hawtio-online should ideally be part of user applications and thus share the same authentication mechanism with them.

**Comment by tadayosi** [comment]
Part of the current awkwardness around RBAC should also be improved with this enhancement, as it will facilitate better integration with RBAC provided by the apps themselves.

**Comment by astefanutti** [comment]
I totally agree. Deeper RBAC integration would be awesome also. Let me close #31 in favour of this.
